name: Update Daily Deals

on:
  schedule:
    # Runs every day at 6:00 AM UTC
    - cron: '0 6 * * *'
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: write # Needed to commit and push changes

jobs:
  update-deals:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use a recent LTS version
          cache: 'npm' # Optional: cache npm dependencies if you add any

      - name: Run fetch deals script
        id: fetch
        run: node fetch-deals.js
        # Continue even if the script logs errors (sets process.exitCode = 1)
        continue-on-error: true 

      - name: Commit and push if changes
        # Only run if the fetch step succeeded OR failed gracefully (didn't crash)
        # and if deals.json actually changed
        if: steps.fetch.outcome == 'success' || steps.fetch.outcome == 'failure' 
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add deals.json
          # Check if there are changes to commit
          if ! git diff --staged --quiet; then
            git commit -m "chore: Update daily game deals"
            git push
          else
            echo "No changes to commit."
          fi 